
language: python
sudo: required
python:
  - "2.7"
install:
  - pip install coveralls
script:
  - "cd lterm"
  - "sudo python term.py -h"
  - "sudo nosetests --with-coverage"
after_success:
  - coveralls
