
language: python
sudo: required
python:
  - "2.7"
install:
  - pip install nose
  - pip install coveralls
script:
  - "cd lterm"
  - "sudo python lterm.py -h"
  - sudo nosetests --exe --with-coverage
after_success:
  - coveralls
