
language: python
sudo: required
python:
  - "2.7"
install:
  - sudo pip install nose
  - sudo pip install coveralls
  - sudo pip install coverage 
script:
  - sudo nosetests --with-coverage --cover-package=lterm
after_success:
  - coveralls
